### ISSUE TITLE
Prefix with kernel environment by default

### ISSUE THREAD

**Issue by rvanlaak** [EmanueleMinotto/TwigCacheBundle#15]
We have multiple development-environments on one machine and make use of APCu. This resulted in cache key collisions because the keys aren't prefixed by default, so we had to implement our own "prefix strategy":

``` php
use Asm89\Twig\CacheExtension\CacheStrategy\IndexedChainingCacheStrategy;

/**
 * Prefix the key while instantiating strategy with the Symfony kernel environment.
 */
class PrefixCacheStrategy extends IndexedChainingCacheStrategy
{
    private $prefix;

    public function generateKey($annotation, $value)
    {
        $annotation = $this->prefix . '_' . $annotation;
        return parent::generateKey($annotation, $value);
    }

    public function setPrefix($prefix)
    {
        $this->prefix = $prefix;
    }
}
```

Service definition:

``` yml
app.twig.strategy.prefix:
    class: 'AppBundle\Twig\PrefixCacheStrategy'
    arguments:
         - { time: '@twig_cache.strategy.lifetime', gen: '@twig_cache.strategy.generational' }
    public: false
    calls:
        - [setPrefix, ['%kernel.environment%']]
```

Given you also choose `IndexedChainingCacheStrategy` as a default, what about prefixing the keys with the Symfony kernel environment by default too?
