### ISSUE TITLE
How this is settings up???

### ISSUE THREAD

**Issue by Slavenin** [EmanueleMinotto/TwigCacheBundle#18]
Hi!
I try use this bundle. 
I do all by guide:
add in config:
```yml
twig_cache:
    service: 'asm89_cache'
```
add in parameters:
```yml
twig_cache.adapter.class: Asm89\Twig\CacheExtension\CacheProvider\PsrCacheAdapter
```
add in services:
```yml
    asm89_cache:
        class: Asm89\Twig\CacheExtension\Extension
        arguments: ["@twig_cache.strategy.lifetime"]
        tags:
           - { name: twig.extension }
```
and i see exception:
```
ServiceCircularReferenceException in CheckCircularReferencesPass.php line 69:
Circular reference detected for service "asm89_cache", path: "asm89_cache -> twig_cache.strategy.lifetime -> twig_cache.adapter -> asm89_cache".
```
What i do wrong?
