### ISSUE TITLE
Redis Setup

### ISSUE THREAD

**Issue by 2case** [EmanueleMinotto/TwigCacheBundle#4]
It was a little bit tricky to setup the cache with redis as backend. Just in case u search for this also here my solution. You have to define two services, one for redis the other for the cache service as described:

```
Vendor/Bundle/Resources/services.yml
    services:
        vendor.bundle.cache.redis:
            class: Redis
            calls:
                - [ connect, [ 'localhost' ]  ]

        vendor.bundle.cache.twig:
            class: Doctrine\Common\Cache\RedisCache
            calls:
                - [ setRedis, [ '@vendor.bundle.cache.redis' ] ]
```
